### ISSUE TITLE
NoMethodError for Sidekiq’s ActionMailer extensions with newrelic_rpm 3.8.1.221

### ISSUE THREAD

**Issue by parhamr** [newrelic/newrelic-ruby-agent#168]
See https://github.com/mperham/sidekiq/issues/1731

Version `3.8.1.221` of `newrelic_rpm` breaks the `Class.delay.method` extension of Sidekiq. The highest version of `newrelic_rpm` that I’ve seen it working in is `3.7.3.204`. I’m not sure how many of the Sidekiq extensions are broken, but I’ve seen the issue with `ActionMailer` in this backtrace…

```
2014-05-23T18:36:08Z 21342 TID-1e1oy6 ERROR: Sidekiq::Processor crashed!
NoMethodError: undefined method `:ending' for "RedactedMailer":String
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/extensions/action_mailer.rb:17:in `perform'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/newrelic_rpm-3.8.1.221/lib/new_relic/agent/instrumentation/sidekiq.rb:32:in `block in call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/newrelic_rpm-3.8.1.221/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:357:in `perform_action_with_newrelic_trace'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/newrelic_rpm-3.8.1.221/lib/new_relic/agent/instrumentation/sidekiq.rb:26:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/logging.rb:22:in `with_context'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `invoke'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:108:in `stats'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:47:in `block in process'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/future.rb:14:in `block in new'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
        (celluloid):0:in `remote procedure call'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/future.rb:104:in `value'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/future.rb:68:in `value'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid.rb:456:in `defer'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:84:in `do_defer'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:37:in `process'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
        /data/redacted/shared/bundled_gems/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```
