### ISSUE TITLE
Agent does not work with RackApp on Ruby 2.7

### ISSUE THREAD

**Issue by mitnal** [newrelic/newrelic-ruby-agent#486]
The new relic agent does not work together with [RackApp](http://www.rack-app.com) on ruby 2.7.

## Description

After upgrading to Ruby 2.7 our App did not start anymore in production env. After digging around it seems that one of the ruby 2.7 fixes splats an argument and the RackApp argument is 'converted' to a hash. RackApp then calls `serialize` on the argument expecting it would be a custom RackApp class, but instead it is a hash. This results in `undefined method 'serializer' for #<Hash:0x00007fa43fb8c758> (NoMethodError)` and the app does not start.

Because we have no problems running this combination in Ruby 2.6 I think the problem is the splat here int the Ruby 2.7 path:
https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/middleware_proxy.rb#L30-L40

## Expected Behavior

No `NoMethodError` when using the ruby agent and Rack App in the same app. The agent should not change arguments to rack apps (in this case it should not convert it to a hash).

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]

Traceback from test app.
```
rails s
=> Booting Puma
=> Rails 6.0.3.4 application starting in production
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	96: from bin/rails:9:in `<main>'
	95: from [...]/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	94: from [...]/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	93: from [...]/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	92: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	91: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	90: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	89: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	88: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	87: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
	86: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	85: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	84: from [...]/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	83: from [...]/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	82: from [...]/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	81: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	80: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
	79: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	78: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:39:in `start'
	77: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	76: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	75: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	74: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	73: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	72: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	71: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	70: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	69: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	68: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	67: from config.ru:3:in `block in <main>'
	66: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	65: from [...]/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	64: from [...]/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	63: from [...]/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	62: from [...]/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	61: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	60: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	59: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	58: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	57: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	56: from [...]/workspace/nr-rackapp-test/config/environment.rb:5:in `<main>'
	55: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
	54: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
	53: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	52: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	51: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	50: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
	49: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
	48: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	47: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	46: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	45: from [...]/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	44: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	43: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
	42: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
	41: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
	40: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:10:in `execute'
	39: from [...]/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/file_update_checker.rb:83:in `execute'
	38: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:29:in `block in updater'
	37: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:20:in `reload!'
	36: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	35: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `each'
	34: from [...]/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	33: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	32: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	31: from [...]/workspace/nr-rackapp-test/config/routes.rb:3:in `<main>'
	30: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	29: from [...]/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	28: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	27: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	26: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	24: from [...]/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	23: from [...]/workspace/nr-rackapp-test/lib/hello_world.rb:5:in `<main>'
	22: from [...]/workspace/nr-rackapp-test/lib/hello_world.rb:7:in `<class:HelloWorld>'
	21: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/singleton_methods/http_methods.rb:6:in `get'
	20: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/singleton_methods/route_handling.rb:23:in `add_route'
	19: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router.rb:25:in `register_endpoint!'
	18: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router.rb:83:in `compile_endpoint!'
	17: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router/tree.rb:17:in `add'
	16: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router/tree/branch.rb:8:in `set'
	15: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router/tree/leaf.rb:15:in `set'
	14: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router/tree/leaf.rb:35:in `save_endpoint'
	13: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router/tree/leaf.rb:44:in `split_save_to_extnames'
	12: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router/tree/vein.rb:5:in `set'
	11: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/router/tree/vein.rb:23:in `create_app'
	10: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/endpoint.rb:34:in `to_app'
	 9: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/endpoint/builder.rb:10:in `to_app'
	 8: from [...]/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/instrumentation/rack.rb:138:in `to_app_with_newrelic_deferred_dependency_detection'
	 7: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:235:in `to_app'
	 6: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:235:in `inject'
	 5: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:235:in `each'
	 4: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:235:in `block in to_app'
	 3: from [...]/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:158:in `block in use'
	 2: from [...]/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/instrumentation/middleware_proxy.rb:37:in `new'
	 1: from [...]/.rvm/gems/ruby-2.7.2/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/instrumentation/middleware_proxy.rb:37:in `new'
[...]/.rvm/gems/ruby-2.7.2/gems/rack-app-7.6.4/lib/rack/app/middlewares/configuration.rb:8:in `initialize': undefined method `serializer' for #<Hash:0x00007fa43fb8c758> (NoMethodError)
```

## Steps to Reproduce

Simple Rails Test App.
New Rails App, just added RackApp with a dummy endpoint (hello_world.rb) and then added the agent. Without agent the app works, with agent the app crashes. 

https://github.com/mitnal/nr-rackapp-test

Clone test rails app, bundle, and just run `rails s`.

In our real app the problem only occurred in production env (I think because of the agent configuration) but the test app also crashes in development. If not try: `RAILS_ENV=production rails s`.

## Your Environment

ruby 2.7.2p137
rails (6.0.3.4)
newrelic_rpm (6.13.1)
rack-app (7.6.4)
rack (2.2.3)

I can reproduce this problem locally on my Mac and also on Heroku so it should be OS independent.

**Comment by tannalynn** [comment]
Hello, @mitnal  
I really appreciate the linked repo for reproducing this issue, and I can confirm that I am seeing the same issue when using newrelic on it. The secion of code for the 2.7 kwarg warnings that you pointed out does seem to be related to the problem based on my testing. This is related to some of our other upcoming work in our bug smash. I linked it to that milestone so we can take a closer look into this issue. 
Thank you for bringing this to our attention

**Comment by mastermatt** [comment]
I came across this issue when I ran into similar issues, objects being converted to plain hashes.
However, we were already running ruby-2.7.0 and nr-6.10.0.364. The issue started when upgrading nr to at least 6.11.0.365. The issue remains on ruby-2.7.2.
[diff](https://github.com/newrelic/newrelic-ruby-agent/compare/6.10.0.364...6.11.0.365)

**Comment by mwlang** [comment]
When adapting the agent for Ruby 2.7, we were over-zealous in making changes to support Ruby 2.7.  Rack, and therefore, RackApp do not pass keyword arguments, so it was unnecessary change to double-splat the last argument in the rack instrumentation.

I believe this is fixed and I verified the fix against a simple RackApp across all the Rubies, but would definitely appreciate feedback from anyone (@mastermatt or @mitnal) affected.  If you have time to test, here's how you can do so:

Update your Gemfile to:
```ruby
gem 'newrelic_rpm', 
  git: 'https://github.com/newrelic/newrelic-ruby-agent.git', 
  branch: '486_rack_app_fix'
```
and `bundle install` and give it a whirl.  If this resolves your issues and does not generate deprecation warnings in Ruby 2.7, then we're good to go.

**Comment by mitnal** [comment]
Hi @mwlang this works without problems in our production and the test app. Thanks. 

If I reactivated the deprecation warnings correctly on 2.7.2 then there are no deprecation warnings 😉.

**Comment by mwlang** [comment]
@mitnal thank you for verifying the changes work.
